// Generated by scripts/sync-model-pricing.ts — do not edit.
// Snapshot date: 2026-07-25. Source: /tmp/models-dev.json.

import type { ModelPricingTable } from "./model-pricing";

export const modelPricingSnapshot: ModelPricingTable = Object.freeze({
  "anthropic/claude-fable-5": {
    "contextLimit": 1000000,
    "cost": {
      "cacheRead": 1,
      "cacheWrite": 12.5,
      "input": 10,
      "output": 50
    }
  },
  "anthropic/claude-haiku-4-5": {
    "contextLimit": 200000,
    "cost": {
      "cacheRead": 0.1,
      "cacheWrite": 1.25,
      "input": 1,
      "output": 5
    }
  },
  "anthropic/claude-haiku-4-5-20251001": {
    "contextLimit": 200000,
    "cost": {
      "cacheRead": 0.1,
      "cacheWrite": 1.25,
      "input": 1,
      "output": 5
    }
  },
  "anthropic/claude-opus-4-5": {
    "contextLimit": 200000,
    "cost": {
      "cacheRead": 0.5,
      "cacheWrite": 6.25,
      "input": 5,
      "output": 25
    }
  },
  "anthropic/claude-opus-4-5-20251101": {
    "contextLimit": 200000,
    "cost": {
      "cacheRead": 0.5,
      "cacheWrite": 6.25,
      "input": 5,
      "output": 25
    }
  },
  "anthropic/claude-opus-4-6": {
    "contextLimit": 1000000,
    "cost": {
      "cacheRead": 0.5,
      "cacheWrite": 6.25,
      "input": 5,
      "output": 25
    }
  },
  "anthropic/claude-opus-4-7": {
    "contextLimit": 1000000,
    "cost": {
      "cacheRead": 0.5,
      "cacheWrite": 6.25,
      "input": 5,
      "output": 25
    }
  },
  "anthropic/claude-opus-4-8": {
    "contextLimit": 1000000,
    "cost": {
      "cacheRead": 0.5,
      "cacheWrite": 6.25,
      "input": 5,
      "output": 25
    }
  },
  "anthropic/claude-sonnet-4-5": {
    "contextLimit": 1000000,
    "cost": {
      "cacheRead": 0.3,
      "cacheWrite": 3.75,
      "input": 3,
      "output": 15
    }
  },
  "anthropic/claude-sonnet-4-5-20250929": {
    "contextLimit": 1000000,
    "cost": {
      "cacheRead": 0.3,
      "cacheWrite": 3.75,
      "input": 3,
      "output": 15
    }
  },
  "anthropic/claude-sonnet-4-6": {
    "contextLimit": 1000000,
    "cost": {
      "cacheRead": 0.3,
      "cacheWrite": 3.75,
      "input": 3,
      "output": 15
    }
  },
  "anthropic/claude-sonnet-5": {
    "contextLimit": 1000000,
    "cost": {
      "cacheRead": 0.2,
      "cacheWrite": 2.5,
      "input": 2,
      "output": 10
    }
  },
  "google/gemini-2.5-flash": {
    "contextLimit": 1048576,
    "cost": {
      "cacheRead": 0.03,
      "input": 0.3,
      "output": 2.5
    }
  },
  "google/gemini-2.5-flash-lite": {
    "contextLimit": 1048576,
    "cost": {
      "cacheRead": 0.01,
      "input": 0.1,
      "output": 0.4
    }
  },
  "google/gemini-2.5-pro": {
    "contextLimit": 1048576,
    "cost": {
      "cacheRead": 0.125,
      "input": 1.25,
      "output": 10
    }
  },
  "google/gemini-3-flash-preview": {
    "contextLimit": 1048576,
    "cost": {
      "cacheRead": 0.05,
      "input": 0.5,
      "output": 3
    }
  },
  "google/gemini-3-pro-preview": {
    "contextLimit": 1048576,
    "cost": {
      "cacheRead": 0.2,
      "input": 2,
      "output": 12
    }
  },
  "google/gemini-3.1-flash-lite": {
    "contextLimit": 1048576,
    "cost": {
      "cacheRead": 0.025,
      "input": 0.25,
      "output": 1.5
    }
  },
  "google/gemini-3.1-pro-preview": {
    "contextLimit": 1048576,
    "cost": {
      "cacheRead": 0.2,
      "input": 2,
      "output": 12
    }
  },
  "google/gemini-3.5-flash": {
    "contextLimit": 1048576,
    "cost": {
      "cacheRead": 0.15,
      "input": 1.5,
      "output": 9
    }
  },
  "google/gemini-flash-latest": {
    "contextLimit": 1048576,
    "cost": {
      "cacheRead": 0.15,
      "input": 1.5,
      "output": 9
    }
  },
  "google/gemini-flash-lite-latest": {
    "contextLimit": 1048576,
    "cost": {
      "cacheRead": 0.025,
      "input": 0.25,
      "output": 1.5
    }
  },
  "google/gemma-4-31b-it": {
    "contextLimit": 262144
  },
  "openai/gpt-5": {
    "contextLimit": 400000,
    "cost": {
      "cacheRead": 0.125,
      "input": 1.25,
      "output": 10
    }
  },
  "openai/gpt-5-codex": {
    "contextLimit": 400000
  },
  "openai/gpt-5-mini": {
    "contextLimit": 400000,
    "cost": {
      "cacheRead": 0.025,
      "input": 0.25,
      "output": 2
    }
  },
  "openai/gpt-5-nano": {
    "contextLimit": 400000,
    "cost": {
      "cacheRead": 0.005,
      "input": 0.05,
      "output": 0.4
    }
  },
  "openai/gpt-5-pro": {
    "contextLimit": 400000,
    "cost": {
      "input": 15,
      "output": 120
    }
  },
  "openai/gpt-5.1": {
    "contextLimit": 400000,
    "cost": {
      "cacheRead": 0.125,
      "input": 1.25,
      "output": 10
    }
  },
  "openai/gpt-5.1-chat-latest": {
    "contextLimit": 400000
  },
  "openai/gpt-5.1-codex": {
    "contextLimit": 400000
  },
  "openai/gpt-5.1-codex-max": {
    "contextLimit": 400000
  },
  "openai/gpt-5.2": {
    "contextLimit": 400000,
    "cost": {
      "cacheRead": 0.175,
      "input": 1.75,
      "output": 14
    }
  },
  "openai/gpt-5.2-chat-latest": {
    "contextLimit": 128000,
    "cost": {
      "cacheRead": 0.175,
      "input": 1.75,
      "output": 14
    }
  },
  "openai/gpt-5.2-codex": {
    "contextLimit": 400000
  },
  "openai/gpt-5.2-pro": {
    "contextLimit": 400000,
    "cost": {
      "input": 21,
      "output": 168
    }
  },
  "openai/gpt-5.3-codex": {
    "contextLimit": 400000,
    "cost": {
      "cacheRead": 0.175,
      "input": 1.75,
      "output": 14
    }
  },
  "openai/gpt-5.3-codex-spark": {
    "contextLimit": 128000,
    "cost": {
      "cacheRead": 0.175,
      "input": 1.75,
      "output": 14
    }
  },
  "openai/gpt-5.4": {
    "contextLimit": 1050000,
    "cost": {
      "cacheRead": 0.25,
      "input": 2.5,
      "output": 15
    }
  },
  "openai/gpt-5.4-mini": {
    "contextLimit": 400000,
    "cost": {
      "cacheRead": 0.075,
      "input": 0.75,
      "output": 4.5
    }
  },
  "openai/gpt-5.4-nano": {
    "contextLimit": 400000,
    "cost": {
      "cacheRead": 0.02,
      "input": 0.2,
      "output": 1.25
    }
  },
  "openai/gpt-5.4-pro": {
    "contextLimit": 1050000,
    "cost": {
      "input": 30,
      "output": 180
    }
  },
  "openai/gpt-5.5": {
    "contextLimit": 1050000,
    "cost": {
      "cacheRead": 0.5,
      "input": 5,
      "output": 30
    }
  },
  "openai/gpt-5.5-pro": {
    "contextLimit": 1050000,
    "cost": {
      "input": 30,
      "output": 180
    }
  },
  "openai/gpt-5.6": {
    "contextLimit": 1050000,
    "cost": {
      "cacheRead": 0.5,
      "cacheWrite": 6.25,
      "input": 5,
      "output": 30
    }
  },
  "openai/gpt-5.6-luna": {
    "contextLimit": 1050000,
    "cost": {
      "cacheRead": 0.1,
      "cacheWrite": 1.25,
      "input": 1,
      "output": 6
    }
  },
  "openai/gpt-5.6-sol": {
    "contextLimit": 1050000,
    "cost": {
      "cacheRead": 0.5,
      "cacheWrite": 6.25,
      "input": 5,
      "output": 30
    }
  },
  "openai/gpt-5.6-terra": {
    "contextLimit": 1050000,
    "cost": {
      "cacheRead": 0.25,
      "cacheWrite": 3.125,
      "input": 2.5,
      "output": 15
    }
  },
  "openai/o1": {
    "contextLimit": 200000,
    "cost": {
      "cacheRead": 7.5,
      "input": 15,
      "output": 60
    }
  },
  "openai/o1-pro": {
    "contextLimit": 200000,
    "cost": {
      "input": 150,
      "output": 600
    }
  },
  "openai/o3": {
    "contextLimit": 200000,
    "cost": {
      "cacheRead": 0.5,
      "input": 2,
      "output": 8
    }
  },
  "openai/o3-mini": {
    "contextLimit": 200000,
    "cost": {
      "cacheRead": 0.55,
      "input": 1.1,
      "output": 4.4
    }
  },
  "openai/o3-pro": {
    "contextLimit": 200000,
    "cost": {
      "input": 20,
      "output": 80
    }
  },
  "openai/o4-mini": {
    "contextLimit": 200000,
    "cost": {
      "cacheRead": 0.275,
      "input": 1.1,
      "output": 4.4
    }
  },
  "opencode-go/deepseek-v4-flash": {
    "contextLimit": 1000000,
    "cost": {
      "cacheRead": 0.0014,
      "input": 0.07,
      "output": 0.14
    }
  },
  "opencode-go/deepseek-v4-pro": {
    "contextLimit": 1000000,
    "cost": {
      "cacheRead": 0.003625,
      "input": 0.435,
      "output": 0.87
    }
  },
  "opencode-go/glm-5.1": {
    "contextLimit": 202752,
    "cost": {
      "cacheRead": 0.26,
      "input": 1.4,
      "output": 4.4
    }
  },
  "opencode-go/glm-5.2": {
    "contextLimit": 1000000,
    "cost": {
      "cacheRead": 0.26,
      "input": 1.4,
      "output": 4.4
    }
  },
  "opencode-go/gpt-5.6-luna": {
    "contextLimit": 1050000,
    "cost": {
      "cacheRead": 0.01,
      "cacheWrite": 0.125,
      "input": 0.1,
      "output": 0.6
    }
  },
  "opencode-go/grok-4.5": {
    "contextLimit": 500000,
    "cost": {
      "cacheRead": 0.5,
      "input": 2,
      "output": 6
    }
  },
  "opencode-go/hy3": {
    "contextLimit": 256000,
    "cost": {
      "cacheRead": 0.035,
      "input": 0.14,
      "output": 0.58
    }
  },
  "opencode-go/kimi-k2.6": {
    "contextLimit": 262144,
    "cost": {
      "cacheRead": 0.16,
      "input": 0.95,
      "output": 4
    }
  },
  "opencode-go/kimi-k2.7-code": {
    "contextLimit": 262144,
    "cost": {
      "cacheRead": 0.19,
      "input": 0.95,
      "output": 4
    }
  },
  "opencode-go/kimi-k3": {
    "contextLimit": 1048576,
    "cost": {
      "cacheRead": 0.3,
      "input": 3,
      "output": 15
    }
  },
  "opencode-go/mimo-v2.5": {
    "contextLimit": 1000000,
    "cost": {
      "cacheRead": 0.0028,
      "input": 0.14,
      "output": 0.28
    }
  },
  "opencode-go/mimo-v2.5-pro": {
    "contextLimit": 1048576,
    "cost": {
      "cacheRead": 0.003625,
      "input": 0.435,
      "output": 0.87
    }
  },
  "opencode-go/minimax-m2.7": {
    "contextLimit": 204800,
    "cost": {
      "cacheRead": 0.06,
      "input": 0.3,
      "output": 1.2
    }
  },
  "opencode-go/minimax-m3": {
    "contextLimit": 1000000,
    "cost": {
      "cacheRead": 0.06,
      "input": 0.3,
      "output": 1.2
    }
  },
  "opencode-go/qwen3.6-plus": {
    "contextLimit": 1000000,
    "cost": {
      "cacheRead": 0.05,
      "cacheWrite": 0.625,
      "input": 0.5,
      "output": 3
    }
  },
  "opencode-go/qwen3.7-max": {
    "contextLimit": 1000000,
    "cost": {
      "cacheRead": 0.5,
      "cacheWrite": 3.125,
      "input": 2.5,
      "output": 7.5
    }
  },
  "opencode-go/qwen3.7-plus": {
    "contextLimit": 1000000,
    "cost": {
      "cacheRead": 0.04,
      "cacheWrite": 0.5,
      "input": 0.4,
      "output": 1.6
    }
  },
  "opencode-go/qwen3.8-max": {
    "contextLimit": 1000000,
    "cost": {
      "cacheRead": 0.25,
      "cacheWrite": 2.5,
      "input": 2,
      "output": 6
    }
  }
});
