#!/usr/bin/env bun
/**
 * Regenerate the bundled model-pricing snapshot and the opencode-go
 * model-variants snapshot.
 *
 * Usage:
 *   WINCODE_MODEL_PRICING_URL=https://models.dev/api.json bun run scripts/sync-model-pricing.ts
 *
 * Default URL: https://models.dev/api.json
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import {
	type ModelVariant,
	modelVariantIds,
	supportedChatModelIds,
	supportedChatModels,
} from "@wincode/ai";
import { billingPricebook } from "@wincode/billing";
import {
	type ModelPricingEntry,
	modelPricingKey,
} from "../apps/cli/src/modules/model-pricing/model-pricing";
import { buildModelPricingTable } from "../apps/cli/src/modules/model-pricing/models-dev-response";

const DEFAULT_URL = "https://models.dev/api.json";

const OVERRIDES: Record<string, ModelPricingEntry> = {
	// OAuth-only models — context limits from public docs, no per-token price.
	"openai/gpt-5-codex": { contextLimit: 400_000 },
	"openai/gpt-5.1-codex": { contextLimit: 400_000 },
	"openai/gpt-5.1-codex-max": { contextLimit: 400_000 },
	"openai/gpt-5.2-codex": { contextLimit: 400_000 },
	"openai/gpt-5.1-chat-latest": { contextLimit: 400_000 },
};

const variantValues = new Set<string>(modelVariantIds);

/**
 * Maps models.dev `reasoning_options` to catalog variants. Effort values are
 * kept in upstream order and filtered to the known variant vocabulary.
 * `toggle` and `budget_tokens` options carry no effort levels, so they
 * contribute nothing — the UI's "Default" state represents reasoning off.
 */
const toModelVariants = (options: unknown): readonly ModelVariant[] => {
	if (!Array.isArray(options)) {
		return [];
	}
	const variants: ModelVariant[] = [];
	for (const option of options) {
		if (option?.type !== "effort") {
			continue;
		}
		for (const value of option.values ?? []) {
			if (
				typeof value === "string" &&
				variantValues.has(value) &&
				!variants.includes(value as ModelVariant)
			) {
				variants.push(value as ModelVariant);
			}
		}
	}
	return variants;
};

const url = process.env.WINCODE_MODEL_PRICING_URL ?? DEFAULT_URL;

const fetchRaw = async (source: string): Promise<unknown> => {
	if (source.startsWith("http")) {
		const response = await fetch(source, {
			headers: { accept: "application/json" },
			signal: AbortSignal.timeout(10_000),
		});
		if (!response.ok) {
			throw new Error(`fetch ${source} → ${response.status}`);
		}
		return response.json();
	}
	return JSON.parse(readFileSync(source, "utf8"));
};

const main = async () => {
	const raw = await fetchRaw(url);
	const ids = new Set<string>(supportedChatModelIds);
	const table = buildModelPricingTable(raw, ids);

	const finalTable: Record<string, ModelPricingEntry> = { ...table };
	let overrideCount = 0;
	for (const [key, entry] of Object.entries(OVERRIDES)) {
		finalTable[key] = entry;
		overrideCount++;
	}

	// Verify every catalog entry has SOME entry under its own (provider, id)
	// key. `endsWith("/id")` would also match a reseller sharing the same
	// literal id under a different provider prefix, so match the exact key.
	const missing: string[] = [];
	for (const model of supportedChatModels) {
		const key = modelPricingKey(model.provider, model.id);
		if (!(key in finalTable)) {
			missing.push(key);
		}
	}

	const microsToUsd = (micros: bigint): number => Number(micros) / 1_000_000;
	for (const id of ["gpt-5.4-mini", "gemini-2.5-flash"]) {
		const live = finalTable[`openai/${id}`] ?? finalTable[`google/${id}`];
		const pricebookEntry =
			billingPricebook.models[id as keyof typeof billingPricebook.models];
		if (pricebookEntry && live?.cost) {
			const expectedInput = microsToUsd(
				pricebookEntry.inputMicrosPerMillionTokens
			);
			const drift = Math.abs(live.cost.input - expectedInput) > 0.01;
			if (drift) {
				console.warn(
					`warning: hosted price drift for ${id}: live=${live.cost.input} pricebook=${expectedInput}`
				);
			}
		}
	}

	const withCost = Object.values(finalTable).filter((e) => e.cost).length;
	const withLimit = Object.values(finalTable).filter(
		(e) => e.contextLimit > 0
	).length;
	const total = Object.keys(finalTable).length;
	console.log(
		`models with cost: ${withCost}/${total} | context limits: ${withLimit}/${total} | overrides: ${overrideCount}`
	);
	if (missing.length > 0) {
		console.warn(
			`warning: ${missing.length} catalog ids have no entry in the snapshot:`,
			missing
		);
	}

	const date = new Date().toISOString().slice(0, 10);
	const outPath = join(
		dirname(new URL(import.meta.url).pathname),
		"..",
		"apps/cli/src/modules/model-pricing/model-pricing-snapshot.generated.ts"
	);
	const serialized = Object.fromEntries(
		Object.entries(finalTable).sort(([a], [b]) => a.localeCompare(b))
	);
	const body = `// Generated by scripts/sync-model-pricing.ts — do not edit.
// Snapshot date: ${date}. Source: ${url}.

import type { ModelPricingTable } from "./model-pricing";

export const modelPricingSnapshot: ModelPricingTable = Object.freeze(${JSON.stringify(serialized, null, 2)});
`;
	writeFileSync(outPath, body);
	console.log(`Wrote ${outPath}`);

	const directVariants: Record<string, readonly ModelVariant[]> = {};
	for (const model of supportedChatModels) {
		if (model.connectionProviderId === "wincode") {
			continue;
		}
		const providerBlock = (
			raw as Record<string, { models?: Record<string, unknown> }>
		)[model.provider];
		const entry = providerBlock?.models?.[model.id];
		directVariants[`${model.connectionProviderId}/${model.id}`] =
			toModelVariants(
				entry instanceof Object ? entry.reasoning_options : undefined
			);
	}
	const variantsPath = join(
		dirname(new URL(import.meta.url).pathname),
		"..",
		"packages/ai/src/generated/model-variants.generated.ts"
	);
	mkdirSync(dirname(variantsPath), { recursive: true });
	const variantsBody = `// Generated by scripts/sync-model-pricing.ts — do not edit.
// Snapshot date: ${date}. Source: ${url}.

export const modelVariantsByProviderModel = ${JSON.stringify(directVariants, null, 2)} as const;
`;
	writeFileSync(variantsPath, variantsBody);
	console.log(`Wrote ${variantsPath}`);
};

void main().catch((error) => {
	console.error(error);
	process.exit(1);
});
