// Assembles the generated model metadata module from the shared models.dev
// converter plus the manual overlays. Fetching lives in
// `sync-model-metadata.ts`; interpretation lives in `../src/models-dev.ts`.

import type { ModelMetadataEntry } from "../src/model-metadata";
import { metadataForModel } from "../src/models-dev";
import { modelsDevBlocksFromPayload } from "../src/models-dev-payload";

type CatalogEntry = {
	readonly connectionProviderId: string;
	readonly id: string;
	readonly lifecycle: "active" | "retired";
	readonly provider: string;
};

/**
 * Facts models.dev does not publish. Every key here is a gap that must stay
 * visible rather than being silently defaulted.
 */
export const MANUAL_OVERLAYS: Readonly<Record<string, ModelMetadataEntry>> = {
	"google/gemini-3-pro-preview": {
		thinking: { levels: ["low", "high"] },
	},
	"openai/gpt-5.6": { reasoningSummary: true },
	"openai/gpt-5.6-luna": { reasoningSummary: true },
	"openai/gpt-5.6-sol": { reasoningSummary: true },
	"openai/gpt-5.6-terra": { reasoningSummary: true },
	"opencode-go/gpt-5.6-luna": { reasoningSummary: true },
};

export type BuildInput = {
	readonly catalog: readonly CatalogEntry[];
	readonly generatedAt: string;
	readonly overlays: Readonly<Record<string, ModelMetadataEntry>>;
	readonly payload: unknown;
	readonly source: string;
};

export type BuildResult = {
	/** The in-memory entries that the generated module will export. */
	readonly entries: Readonly<Record<string, ModelMetadataEntry>>;
	readonly contents: string;
	readonly coverage: {
		readonly activeEntries: number;
		readonly absentUpstream: readonly string[];
		readonly fromOverlay: readonly string[];
		readonly fromSource: number;
		readonly retiredEntries: number;
		/** Absent upstream with no overlay either: the entries with nothing. */
		readonly uncovered: readonly string[];
	};
};

/**
 * Builds the generated metadata module plus a coverage summary. Active catalog
 * entries with no upstream model are reported; retired entries retain any
 * available source or overlay metadata so persisted variants can be restored.
 */
export const buildModelMetadataFile = (input: BuildInput): BuildResult => {
	const blocks = modelsDevBlocksFromPayload(input.payload);
	const rows: Record<string, ModelMetadataEntry> = {};
	const absentUpstream: string[] = [];
	const uncovered: string[] = [];
	const fromOverlay: string[] = [];
	let activeEntries = 0;
	let fromSource = 0;
	let retiredEntries = 0;

	for (const entry of input.catalog) {
		const key = `${entry.connectionProviderId}/${entry.id}`;
		const upstream = blocks.get(entry.provider)?.get(entry.id);
		const overlay = input.overlays[key];
		const sourceMetadata = upstream ? metadataForModel(upstream) : undefined;
		const upstreamMetadata =
			sourceMetadata && Object.keys(sourceMetadata).length > 0
				? sourceMetadata
				: undefined;
		if (entry.lifecycle !== "active") {
			rows[key] = { ...upstreamMetadata, ...overlay };
			retiredEntries += 1;
			continue;
		}
		activeEntries += 1;
		if (upstreamMetadata) {
			fromSource += 1;
		} else {
			absentUpstream.push(key);
			// An overlay covering the gap is not the same as nothing covering
			// it, and only the latter is a problem worth naming in the header.
			if (!overlay) {
				uncovered.push(key);
			}
		}
		if (overlay) {
			fromOverlay.push(key);
		}
		rows[key] = { ...upstreamMetadata, ...overlay };
	}

	const header = [
		"// Generated by packages/ai/scripts/sync-model-metadata.ts — do not edit.",
		`// Snapshot date: ${input.generatedAt}. Source: ${input.source}.`,
		`// Catalog: ${activeEntries} active entries (${retiredEntries} retired), ${fromSource} from the source above.`,
		`// Upstream-missing entries (including overlay-covered): ${absentUpstream.join(", ") || "none"}.`,
		"//",
		"// Manual overlays supply facts the source does not publish:",
		`// ${fromOverlay.join(", ") || "none"}.`,
		"// Absent upstream, with no overlay either (reported, never fabricated):",
		`// ${uncovered.join(", ") || "none"}.`,
		`// Absent upstream but overlayed: ${absentUpstream.length - uncovered.length}.`,
		"",
	].join("\n");
	const body = JSON.stringify(rows, null, "\t");
	const contents = `${header}// The build-time age of this data, so a reader can tell how current it is.\nexport const modelMetadataSnapshotDate = ${JSON.stringify(input.generatedAt)};\n\nimport type { ModelMetadataEntry } from "../model-metadata";\n\nexport const modelMetadataByKey: Readonly<\n\tRecord<string, ModelMetadataEntry>\n> = ${body};\n`;

	return {
		contents,
		entries: rows,
		coverage: {
			absentUpstream,
			activeEntries,
			fromOverlay,
			fromSource,
			retiredEntries,
			uncovered,
		},
	};
};
